function cfg = adaptiveSamplingConfig(options)
%adaptiveSamplingConfig Build configuration for adaptive sampling workflow.
%
%   cfg = adaptiveSamplingConfig() returns a struct with default parameters
%   suitable for the adaptive sampling orchestration workflow.
%
%   cfg = adaptiveSamplingConfig(Name=Value) customizes any parameter.
%   Metric names support scalar variants and are extracted via extractSamplingMetrics.
%
%   The DataSource parameter selects the inference engine for querying new
%   points generated by rejection sampling:
%     "interpolation" (default) — makima interpolation from raw COMSOL data
%     "model"                   — DNN inference from a trained model file
%
%   Example (CLI — interpolation from raw data):
%       cfg = adaptiveSamplingConfig( ...
%           WorkDir="D:\data", DataFile="prl_sweep.mat", ...
%           MetricNames=["EF_vol_avg", "Absorptance"], ...
%           MetricWeights=[0.7, 0.3], NumPoints=200);
%
%   Example (CLI — model inference):
%       cfg = adaptiveSamplingConfig( ...
%           DataSource="model", ModelFile="sers_model.mat", ...
%           DataFile="prl_sweep.mat", NumPoints=200);
%
%   See also: runAdaptiveSamplingWorkflow, createSamplingConfig,
%             extractSamplingMetrics, ProgressReporter, buildPredictorFromConfig

arguments
    %% Data source
    options.WorkDir         (1,1) string  = pwd
    options.DataSource      (1,1) string {mustBeMember(options.DataSource, ...
        ["model", "interpolation"])} = "interpolation"
    options.DataFile        (1,1) string  = ""
    options.ModelFile       (1,1) string  = ""
    options.RiCsvFile       (1,1) string  = ""
    options.PredictionFile  (1,1) string  = ""

    %% Backward compat (deprecated)
    options.FromPredictions (1,1) logical = false

    %% Sampling parameters
    options.NumPoints              (1,1) double {mustBePositive, mustBeInteger} = 100
    options.MaxAttempts            (1,1) double {mustBePositive}                = 1e6
    options.MinSeparation          (1,1) double {mustBeNonnegative}             = 0.2
    options.RtpThreshold           (1,1) double {mustBeNonnegative}             = 0.49
    options.UniformSampling        (1,1) logical                               = true
    options.EnforceOriginalSpacing (1,1) logical                               = false

    %% Parameter ranges
    options.PeriodRange (1,2) double = [NaN, NaN]
    options.RadiusRange (1,2) double = [NaN, NaN]

    %% Metric configuration (density guidance)
    options.MetricNames     (1,:) string = "EF_vol"
    options.MetricWeights   (1,:) double = 1
    options.MetricAlphas    (1,:) double = 1
    options.OverallExponent (1,1) double = 1
    options.BlurSigma       (1,1) double {mustBeNonnegative} = 0

    %% Output / export
    options.OutputFile      (1,1) string = "adaptive_sweep_points.txt"
    options.ParamNames      (1,:) string = ["period", "particle_r"]
    options.ParamUnits      (1,:) string = ["[nm]", "[nm]"]
    options.IncludeOriginal (1,1) logical = false
    options.Precision       (1,1) double {mustBePositive, mustBeInteger} = 6

    %% Visualisation
    options.Visualize       (1,1) logical = true
    options.ColormapFile    (1,1) string  = ""
    options.GridResolution  (1,1) double {mustBePositive, mustBeInteger} = 500

    %% Advanced
    options.DensityThreshold (1,1) double {mustBeNonnegative} = 0
    options.xAxisParam       (1,1) string = ""
    options.yAxisParam       (1,1) string = ""
end

    %% Handle deprecated FromPredictions
    if options.FromPredictions
        warning("adaptiveSamplingConfig:DeprecatedFromPredictions", ...
            "FromPredictions is deprecated. Use DataSource='interpolation' with DataFile instead.");
    end

    %% Prepare metric names
    % Preserve user-specified metric names (e.g. EF_vol_avg, EF_vol_laser, BEE_vol)
    % so that multi-metric configurations and specific scalar variants are not collapsed.
    if iscell(options.MetricNames)
        while isscalar(options.MetricNames) && iscell(options.MetricNames{1})
            options.MetricNames = options.MetricNames{1};
        end
        metricNames = string(options.MetricNames);
    else
        metricNames = string(options.MetricNames);
    end
    metricNames = metricNames(~ismissing(metricNames) & strlength(strtrim(metricNames)) > 0);
    if isempty(metricNames)
        metricNames = "EF_vol_avg";
    end

    %% Delegate to createSamplingConfig for core validation
    %  Pass fromPredictions=false always; data source is handled at the
    %  orchestration level now.
    coreCfg = createSamplingConfig( ...
        dataFile          = options.DataFile, ...
        fromPredictions   = false, ...
        predictionFile    = options.PredictionFile, ...
        numPoints         = options.NumPoints, ...
        maxAttempts       = options.MaxAttempts, ...
        minSeparation     = options.MinSeparation, ...
        rtpThreshold      = options.RtpThreshold, ...
        uniformSampling   = options.UniformSampling, ...
        enforceOriginalSpacing = options.EnforceOriginalSpacing, ...
        periodRange       = options.PeriodRange, ...
        radiusRange       = options.RadiusRange, ...
        metricNames       = cellstr(metricNames), ...
        metricWeights     = options.MetricWeights, ...
        metricAlphas      = options.MetricAlphas, ...
        overallExponent   = options.OverallExponent, ...
        blurSigma         = options.BlurSigma, ...
        outputFile        = options.OutputFile, ...
        paramNames        = cellstr(options.ParamNames), ...
        paramUnits        = cellstr(options.ParamUnits), ...
        includeOriginal   = options.IncludeOriginal, ...
        densityThreshold  = options.DensityThreshold, ...
        gridResolution    = options.GridResolution, ...
        xAxisParam        = options.xAxisParam, ...
        yAxisParam        = options.yAxisParam);

    %% Augment with orchestration-level fields
    cfg = coreCfg;
    cfg.workDir         = options.WorkDir;
    cfg.dataSource      = options.DataSource;
    cfg.dataFile        = options.DataFile;
    cfg.modelFile       = options.ModelFile;
    cfg.riCsvFile       = options.RiCsvFile;
    cfg.predictionFile  = options.PredictionFile;
    cfg.visualize       = options.Visualize;
    cfg.colormapFile    = options.ColormapFile;
    cfg.precision       = options.Precision;
    cfg.gridResolution  = options.GridResolution;
    cfg.xAxisParam      = options.xAxisParam;
    cfg.yAxisParam      = options.yAxisParam;

end