% test_replace_existing_import.m - Test ReplaceExisting option in import workflow
setup_project;

testDir = fileparts(mfilename('fullpath'));
sourceFile = "SweepPropeTable.dat";
outMat = fullfile(tempdir, "test_replace_existing.mat");
if isfile(outMat), delete(outMat); end

%% 1. Initial import: Rebuild mode
cfg1 = importSweepConfig( ...
    WorkDir = testDir, ...
    InputFile = sourceFile, ...
    OutputFile = outMat, ...
    LaserWavelength = 785, ...
    Mode = "rebuild");
res1 = runImportSweepWorkflow(cfg1, ProgressReporter.silent());
totalInit = res1.summary.numEntries;
assert(totalInit > 0, "Initial import should produce entries");
fprintf("Initial rebuild import: %d entries created.\n", totalInit);

%% 2. Test A: Merge with ReplaceExisting = false (Default: should skip matching entries)
cfg2 = importSweepConfig( ...
    WorkDir = testDir, ...
    InputFile = sourceFile, ...
    OutputFile = outMat, ...
    LaserWavelength = 785, ...
    Mode = "merge", ...
    ReplaceExisting = false);
res2 = runImportSweepWorkflow(cfg2, ProgressReporter.silent());
fprintf("Test A: skipped=%d, replaced=%d, total=%d\n", ...
    res2.summary.skippedExisting, res2.summary.replacedDuplicates, res2.summary.numEntries);

assert(res2.summary.skippedExisting == totalInit, ...
    sprintf("Expected %d skipped entries by default, got %d", totalInit, res2.summary.skippedExisting));
assert(res2.summary.replacedDuplicates == 0, ...
    sprintf("Expected 0 replaced duplicates, got %d", res2.summary.replacedDuplicates));
assert(res2.summary.numEntries == totalInit, ...
    sprintf("Expected total entries to stay %d, got %d", totalInit, res2.summary.numEntries));
fprintf("Test A PASSED: All %d existing entries were skipped by default (ReplaceExisting = false).\n", totalInit);

%% 3. Test B: Merge with ReplaceExisting = true (Should replace matching entries)
cfg3 = importSweepConfig( ...
    WorkDir = testDir, ...
    InputFile = sourceFile, ...
    OutputFile = outMat, ...
    LaserWavelength = 785, ...
    Mode = "merge", ...
    ReplaceExisting = true);
res3 = runImportSweepWorkflow(cfg3, ProgressReporter.silent());
fprintf("Test B: skipped=%d, replaced=%d, total=%d\n", ...
    res3.summary.skippedExisting, res3.summary.replacedDuplicates, res3.summary.numEntries);

assert(res3.summary.replacedDuplicates == totalInit, ...
    sprintf("Expected %d replaced entries with ReplaceExisting=true, got %d", totalInit, res3.summary.replacedDuplicates));
assert(res3.summary.skippedExisting == 0, ...
    sprintf("Expected 0 skipped entries with ReplaceExisting=true, got %d", res3.summary.skippedExisting));
assert(res3.summary.numEntries == totalInit, ...
    sprintf("Expected total entries to be %d, got %d", totalInit, res3.summary.numEntries));
fprintf("Test B PASSED: All %d existing entries were replaced (ReplaceExisting = true).\n", totalInit);

fprintf("\nAll ReplaceExisting tests PASSED successfully!\n");
