% run_locate_maxima  Locate spectral-average maxima via MultiStart.
%
% Thin CLI entry point that delegates to the modular orchestration layer.
% All domain logic lives in runLocalizationWorkflow; this script only
% assembles configuration and triggers visualisation.
%
% To customise, modify the localizeMaximaConfig call below.
% The same workflow can be called from uihtml apps via:
%     results = runLocalizationWorkflow(cfg, htmlReporter);
%
% See also: localizeMaximaConfig, runLocalizationWorkflow,
%           visualizeMaximaResults, ProgressReporter

%% Configuration
workDir = string(pwd);

cfg = localizeMaximaConfig( ...
    WorkDir=workDir, ...
    ModelFile="sers_dnn_model_sphere_785_new.mat", ...
    RiCsvFile="McPeak.csv", ...
    PredictionFile="sers_dnn_model_sphere_785_new.mat_predictions.mat", ...
    ...
    ... % Grid parameters
    LambdaLaser=785, ...
    PLimits=[850, 920], ...
    RLimits=[70, 430], ...
    StokesShiftLimits=[0, 0], ...
    Resolution=0.7, ...
    StokesShiftResolution=1, ...
    ...
    ... % Metrics & constraints
    MetricsToLocate=["Absorptance", "EF_vol", "EF_surf"], ...
    RatioLimit=[0, 0.49], ...
    ...
    ... % Prediction control
    RecomputePredictions=true, ...
    ...
    ... % MultiStart parameters
    NumLocalMaxima=15, ...
    MultiStartPoints=1000, ...
    MultiStartUseParallel=true, ...
    MultiStartDisplay="off", ...
    FunctionTolerance=1e-9, ...
    StepTolerance=1e-9, ...
    MaxIterations=1e4, ...
    ...
    ... % Candidate detection
    GradientPercentile=1, ...
    LaplacianFactor=0.5, ...
    NeighborSuppressionRadius=3, ...
    LocalWindowRadiusSteps=6, ...
    MinLocalWindow=0.001, ...
    NeighborTolerance=1e-9);

%% Run workflow
reporter = ProgressReporter.console();
results = runLocalizationWorkflow(cfg, reporter);

%% Display results
for mIdx = 1:numel(results.metrics)
    mr = results.metrics{mIdx};
    fprintf('\n========== %s ==========\n', mr.metricName);
    if ~isempty(mr.candidateTable) && height(mr.candidateTable) > 0
        fprintf('Candidates (%d):\n', height(mr.candidateTable));
        disp(mr.candidateTable);
    end
    if ~isempty(mr.maximaResults) && height(mr.maximaResults) > 0
        fprintf('Refined maxima (%d):\n', height(mr.maximaResults));
        disp(mr.maximaResults);
    end
end

%% Visualise
visualizeMaximaResults(results, ExportDir=workDir);
