%% run_dnn_pipeline — Thin CLI wrapper for DNN training workflow
%
% Delegates to trainingConfig + runTrainingWorkflow.
% Edit the Name-Value pairs below for your project, then Run.
%
% See also: trainingConfig, runTrainingWorkflow, visualizeTrainingResults

%% Configuration -----------------------------------------------------------
cfg = trainingConfig( ...
    WorkDir             = string(pwd), ...
    RawDataFiles        = "prl_sweep_sphere_785_new.mat", ...
    RICsvFile           = "McPeak.csv", ...
    OutputModelFile     = "sers_dnn_model_sphere_785_new.mat", ...
    PreTrainedModelFile = "sers_dnn_model_sphere_785_new.mat", ...
    ContinueTraining    = true, ...
    RatioLimit          = [0, 0.49], ...
    MetricsToTrain      = ["Absorptance", "EF_vol", "EF_surf"], ...
    MaxEpochs           = 50000, ...
    MiniBatchSize       = 1024, ...
    LearningRate        = 1e-4, ...
    Verbose             = true, ...
    Holdout             = 0.1, ...
    ValSplit            = 0.9, ...
    SaveArtifacts       = true ...
);

%% Run workflow ------------------------------------------------------------
results = runTrainingWorkflow(cfg, ProgressReporter.console());

%% Visualize results -------------------------------------------------------
visualizeTrainingResults(results);
