%% run_import_prl_sweep — Thin CLI wrapper for COMSOL sweep import
%
% Delegates to importSweepConfig + runImportSweepWorkflow.
% Edit the Name-Value pairs below for your project, then Run.
%
% See also: importSweepConfig, runImportSweepWorkflow, visualizeImportSummary

%% Configuration -----------------------------------------------------------
cfg = importSweepConfig( ...
    WorkDir             = string(pwd), ...
    InputFile           = "SweepPropeTable.dat", ...
    OutputFile          = "prl_sweep_sphere_785_new.mat", ...
    AnalyteSpectrumFile = "AnalyteSpectrum_electrolyte.dat", ...
    LaserWavelength     = 785, ...
    RamanWindow         = [100, 3600], ...
    DetectShiftWindow   = false, ...
    InterpResolution    = 1, ...
    Mode                = "merge", ...
    RecalculateExisting = true, ...
    SpaceCorrection     = true, ...
    CellHeight          = 4000 ...
);

%% Run workflow ------------------------------------------------------------
results = runImportSweepWorkflow(cfg, ProgressReporter.console());

%% QA visualization --------------------------------------------------------
visualizeImportSummary(results);

