% run_AdaptiveParameterSampling  Generate adaptive COMSOL parameter sweeps.
%
% Thin CLI entry point that delegates to the modular orchestration layer.
% All domain logic lives in runAdaptiveSamplingWorkflow; this script only
% assembles configuration.
%
% To customise, modify the adaptiveSamplingConfig call below.
% The same workflow can be called from uihtml apps via:
%     results = runAdaptiveSamplingWorkflow(cfg, htmlReporter);
%
% See also: adaptiveSamplingConfig, runAdaptiveSamplingWorkflow,
%           ProgressReporter

clearvars;
clc;

%% Configuration
workDir = string(pwd);

cfg = adaptiveSamplingConfig( ...
    WorkDir=workDir, ...
    DataFile="prl_sweep_sphere_785_new.mat", ...
    FromPredictions=false, ...
    PredictionFile="sers_dnn_model_cylinder_h150_532_all.mat_predictions_(Absorptance_EF_vol_EF_surf).mat", ...
    ...
    ... % Sampling parameters
    NumPoints=100, ...
    MinSeparation=0.2, ...
    RtpThreshold=0.49, ...
    UniformSampling=true, ...
    ...
    ... % Parameter ranges (set both to enable manual range)
    PeriodRange=[902, 907], ...
    RadiusRange=[398, 408], ...
    ...
    ... % Metric-guided sampling (only used when UniformSampling=false)
    MetricNames=["EF_vol_avg", "EF_vol_laser", "Absorptance_laser"], ...
    MetricWeights=[0, 1, 0], ...
    MetricAlphas=[1, 1, 1], ...
    OverallExponent=1, ...
    ...
    ... % Output settings
    OutputFile="adaptive_sweep_points_refined.txt", ...
    ParamNames=["period", "particle_r"], ...
    ParamUnits=["[nm]", "[nm]"], ...
    IncludeOriginal=false);

%% Run workflow
reporter = ProgressReporter.console();
results = runAdaptiveSamplingWorkflow(cfg, reporter);

%% Summary
fprintf("\nGenerated %d points (%.1f%% acceptance) in %.1f s.\n", ...
    results.samplingResult.count, ...
    results.samplingResult.acceptanceRate * 100, ...
    results.elapsedTotal);

