function [names, raw] = defaultComsolVarNames()
raw = {
    'period (nm)'
    'particle_r (nm)'
    'lambda0 (nm)'
    'E_vol (1), <E>vol'
    'E_surf (1), <E>surf'
    'M_vol (1), <M>vol'
    'M_surf (1), <M>surf'
    'M2_vol (1), <M2>vol'
    'M2_surf (1), <M2>surf'
    'EF_vol (1), <EF>vol'
    'EF_surf (1), <EF>surf'
    'intW_vol (neV), <W>vol'
    'intW_t (neV), intW'
    'Absorptance (%), Absorptance'
    'Reflectance (%), Reflectance'
    'Transmittance (%), Transmittance'
    'SD (nm), Skin depth'
    'ECC (%), EC Check'
    'lam0 (nm), Wavelength'
    'Resistive Loss (%), Resistive Loss'
    };
names = {
    'period'
    'radius'
    'lambda'
    'E_vol'
    'E_surf'
    'M_vol'
    'M_surf'
    'M2_vol'
    'M2_surf'
    'EF_vol'
    'EF_surf'
    'intW_vol'
    'intW_t'
    'Absorptance'
    'Reflectance'
    'Transmittance'
    'SkinDepth'
    'ECCheck'
    'Wavelength'
    'ResistiveLoss'
    };
end