function runAdaptiveParameterSamplingPipeline(options)
% runAdaptiveParameterSamplingPipeline  Complete pipeline for adaptive sampling.
%
%   runAdaptiveParameterSamplingPipeline() runs the full adaptive sampling
%   pipeline with default configuration: loads data, builds density model,
%   generates sample points, visualizes results, and exports to COMSOL.
%
%   runAdaptiveParameterSamplingPipeline(Name=Value) allows customization
%   of all pipeline parameters.
%
%   This is the main entry point for the adaptive sampling workflow.
%   Individual steps can also be run separately using the component functions.
%
%   Pipeline Steps:
%       1. Load data (MAT file or DNN predictions)
%       2. Build sampling density function
%       3. Generate points via rejection sampling
%       4. Visualize density and points
%       5. Export points to COMSOL format
%
%   Basic Examples:
%       % Run with defaults
%       runAdaptiveParameterSamplingPipeline();
%
%       % Custom data file and output
%       runAdaptiveParameterSamplingPipeline( ...
%           DataFile="my_sweep.mat", ...
%           NumPoints=500, ...
%           OutputFile="my_points.txt");
%
%       % Metric-guided sampling
%       runAdaptiveParameterSamplingPipeline( ...
%           UniformSampling=false, ...
%           MetricNames={"BEE_vol", "Absorptance"}, ...
%           MetricWeights=[0.8, 0.2]);
%
%   Advanced Example:
%       % Full customization
%       runAdaptiveParameterSamplingPipeline( ...
%           DataFile="sweep_785.mat", ...
%           NumPoints=200, ...
%           PeriodRange=[400, 600], ...
%           RadiusRange=[100, 200], ...
%           MinSeparation=2.0, ...
%           RtpThreshold=0.48, ...
%           UniformSampling=false, ...
%           MetricNames={"BEE_vol"}, ...
%           MetricWeights=1, ...
%           OverallExponent=2, ...
%           OutputFile="refined_sweep.txt", ...
%           IncludeOriginal=true);
%
%   See also: createSamplingConfig, loadSamplingData, buildSamplingDensity,
%             runAdaptiveSampling, visualizeSamplingResults, exportToComsol

arguments
    % Data source
    options.DataFile (1,1) string = ""
    options.FromPredictions (1,1) logical = false
    options.PredictionFile (1,1) string = ""
    options.WorkDir (1,1) string = pwd
    
    % Sampling parameters
    options.NumPoints (1,1) double {mustBePositive, mustBeInteger} = 100
    options.MaxAttempts (1,1) double {mustBePositive} = 1e6
    options.MinSeparation (1,1) double {mustBeNonnegative} = 0.2
    options.RtpThreshold (1,1) double {mustBeNonnegative} = 0.49
    options.UniformSampling (1,1) logical = true
    options.EnforceOriginalSpacing (1,1) logical = false
    
    % Parameter ranges
    options.PeriodRange (1,2) double = [NaN, NaN]
    options.RadiusRange (1,2) double = [NaN, NaN]
    
    % Metric configuration
    options.MetricNames (1,:) cell = {"EF_vol_avg"}
    options.MetricWeights (1,:) double = 1
    options.MetricAlphas (1,:) double = 1
    options.OverallExponent (1,1) double = 1
    options.BlurSigma (1,1) double {mustBeNonnegative} = 0
    
    % Output settings
    options.OutputFile (1,1) string = "adaptive_sweep_points.txt"
    options.ParamNames (1,:) cell = {"period", "particle_r"}
    options.ParamUnits (1,:) cell = {"[nm]", "[nm]"}
    options.IncludeOriginal (1,1) logical = false
    
    % Visualization
    options.Visualize (1,1) logical = true
    options.ColormapFile (1,1) string = ""
    options.GridResolution (1,1) double {mustBePositive, mustBeInteger} = 500
end

fprintf("=== Adaptive Parameter Sampling Pipeline ===\n\n");

% Change to working directory if specified
if options.WorkDir ~= "" && options.WorkDir ~= pwd
    cd(options.WorkDir);
    fprintf("Working directory: %s\n", options.WorkDir);
end

%% Step 1: Create configuration
fprintf("\n--- Step 1: Configuration ---\n");
cfg = createSamplingConfig( ...
    dataFile=options.DataFile, ...
    fromPredictions=options.FromPredictions, ...
    predictionFile=options.PredictionFile, ...
    numPoints=options.NumPoints, ...
    maxAttempts=options.MaxAttempts, ...
    minSeparation=options.MinSeparation, ...
    rtpThreshold=options.RtpThreshold, ...
    uniformSampling=options.UniformSampling, ...
    enforceOriginalSpacing=options.EnforceOriginalSpacing, ...
    periodRange=options.PeriodRange, ...
    radiusRange=options.RadiusRange, ...
    metricNames=options.MetricNames, ...
    metricWeights=options.MetricWeights, ...
    metricAlphas=options.MetricAlphas, ...
    overallExponent=options.OverallExponent, ...
    blurSigma=options.BlurSigma, ...
    outputFile=options.OutputFile, ...
    paramNames=options.ParamNames, ...
    paramUnits=options.ParamUnits, ...
    includeOriginal=options.IncludeOriginal, ...
    gridResolution=options.GridResolution);

fprintf("Configuration created.\n");

%% Step 2: Load data
fprintf("\n--- Step 2: Load Data ---\n");
samples = loadSamplingData(cfg);

%% Step 3: Build density model
fprintf("\n--- Step 3: Build Density Model ---\n");
density = buildSamplingDensity(cfg, samples);

%% Step 4: Run adaptive sampling
fprintf("\n--- Step 4: Generate Sample Points ---\n");
result = runAdaptiveSampling(cfg, samples, density);

%% Step 5: Visualize results
if options.Visualize
    fprintf("\n--- Step 5: Visualize Results ---\n");
    visualizeSamplingResults(cfg, samples, density, result, ...
        GridResolution=options.GridResolution, ...
        ColormapFile=options.ColormapFile, ...
        ShowOriginal=~cfg.fromPredictions);
end

%% Step 6: Export to COMSOL
fprintf("\n--- Step 6: Export Results ---\n");
origPoints = [samples.period(:), samples.radius(:)];
exportToComsol(result, ...
    OutputFile=cfg.outputFile, ...
    ParamNames=cfg.paramNames, ...
    ParamUnits=cfg.paramUnits, ...
    IncludeOriginal=cfg.includeOriginal, ...
    OriginalPoints=origPoints, ...
    FilterToRange=cfg.useManualRange, ...
    PeriodRange=density.periodRange, ...
    RadiusRange=density.radiusRange);

fprintf("\n=== Pipeline Complete ===\n");
fprintf("Generated %d points (%.1f%% acceptance rate)\n", ...
    result.count, 100 * result.acceptanceRate);
fprintf("Output file: %s\n", cfg.outputFile);

end
